- name: 'Allow secure docker swarm node communication (managers only)'
  ufw:
    rule: allow
    port: 2377
    proto: tcp

- name: 'Create primary swarm manager'
  shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
  when: "docker_info.stdout.find('Swarm: inactive') != -1"

- name: 'Get docker swarm manager token'
  shell: docker swarm join-token -q manager
  register: manager_token

- name: 'Get docker swarm worker token'
  shell: docker swarm join-token -q worker
  register: worker_token
  
- hosts: docker-workers
  become: yes
  become_method: sudo
  vars:
    manager_hostname: "{{ groups['docker-manager-first'][0] }}"
  tasks:
    - name: 'Join as a worker'
      shell: "docker swarm join --token {{ hostvars[manager_hostname]['worker_token']['stdout'] }} {{ hostvars[manager_hostname]['ansible_default_ipv4']['address'] }}:2377"
      when: "docker_info.stdout.find('Swarm: inactive') != -1"
      retries: 3
      delay: 20

- hosts: docker-manager-first
  become: yes
  become_method: sudo
  tasks:
    - name: Label nodes
      shell: docker node update --label-add {{ hostvars[hostname]['data_label'] }}=true {{ hostname }}
      loop: "{{ groups['docker-manager-first'] + groups['docker-workers'] }}"
      loop_control:
        loop_var: hostname
      when: hostvars[hostname]['data_label'] is defined