- name: Update apt repository
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Wait for apt lock and upgrade all packages to the latest version
  shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done
    apt-get update && apt-get dist-upgrade -y

- name: Remove unnecessary packages
  apt:
    autoremove: yes

- name: Clean up apt cache
  apt:
    autoclean: yes

- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: present

- name: Configure Unattended Upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Package-Blacklist {};
      Unattended-Upgrade::DevRelease "auto";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };
    owner: root
    group: root
    mode: '0644'
