# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

all:
  vars:
    # This configuration variable blocks all access to the server, including SSH, except from the IP addresses specified below.
    # This should always be set when configuring a production server if there is no other firewall in front of the server.
    # SSH and other services should never be exposed to the public internet.
    # Enable backups
    enable_backups: true
    backup_server_remote_target_directory: /home/backup/backups
    # external_backup_server_ssh_port: Defined in --extra-vars by the provisioning pipeline
    # external_backup_server_ip: Defined in --extra-vars by the provisioning pipeline
    users:
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: my-user
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABg...Z/rhU= user@example.com
        state: present
        sudoer: true
      - name: vmudryi
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgMcsSBwTE0EbMDRSF1T4vJDcN/5HAjKGbi2DqV7g/Q vmudryi@opencrvs.org
        state: present
        sudoer: true
docker-manager-first:
  hosts:
    prod-01: # @todo set this to be the hostname of your target server
      ansible_host: '22.22.22.22' # @todo set this to be the hostname of your target server
      data_label: data1

# We recommend you add 2-4 workers for a scaled production deployment
# This should depend on the size of your country and the number of end users.
# If you are only using one production worker for very small countries or small pilot projects, replace with an empty block like so: docker-workers: {}
docker-workers:
  hosts:
    prod-02: # @todo set this to be the hostname of your target server
      ansible_host: '33.33.33.33'
      # If you are using a jump server to access this environment, enter other SSH args here.
      # ansible_ssh_common_args: '-J jump@55.55.55.55 -o StrictHostKeyChecking=no'

backups:
  hosts:
    backup: # @todo set this to be the hostname of your backup server
      ansible_host: '66.66.66.66'
      # Written by provision pipeline. Assumes "backup" environment
      # exists in Github environments
      ansible_ssh_private_key_file: /tmp/backup_ssh_private_key
