services:
  traefik:
    networks:
      - overlay_net
      # https://go-acme.github.io/lego/dns/route53/ see needed policy privileges and config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
      - AWS_REGION=af-south-1 # https://docs.aws.amazon.com/general/latest/gr/r53.html
    command:
      - --certificatesresolvers.certResolver.acme.dnschallenge=true
      - --certificatesresolvers.certResolver.acme.dnschallenge.provider=route53
      # - --certificatesresolvers.certResolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.certResolver.acme.email=sd-identity@digital.gov.mg
      - --certificatesresolvers.certResolver.acme.storage=acme.json
      - --certificatesresolvers.certResolver.acme.dnschallenge.delayBeforeCheck=600
      - --certificatesresolvers.certResolver.acme.dnschallenge.disablePropagationCheck=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=DEBUG
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --serverstransport.insecureskipverify=true
      - --entrypoints.websecure.address=:443
      - --accesslog=true
      - --accesslog.format=json
      - --ping=true

  notification:
    environment:
      - LANGUAGES=en,fr,mg
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  countryconfig:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION}
    restart: unless-stopped
    secrets:
      - jwt-public-key.{{ts}}
    environment:
      - NODE_ENV=production
      - QA_ENV=true
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - APPLICATION_CONFIG_URL=http://config:2021
      - CONFIRM_REGISTRATION_URL=http://workflow:5050/confirm/registration
      - GATEWAY_URL=http://gateway:7070
      - CHECK_INVALID_TOKEN=true
      - MONGO_URL=mongodb://mongo1/user-mgnt?replicaSet=rs0
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE}
      - NUI_GENERATOR_URL=${NUI_GENERATOR_URL}
      - NUI_CLIENT_ID=${NUI_CLIENT_ID}
      - NUI_CLIENT_SECRET=${NUI_CLIENT_SECRET}
      - NUI_API_KEY=${NUI_API_KEY}
      - X_ROAD_CLIENT=${X_ROAD_CLIENT}
    deploy:
      replicas: 1
    networks:
      - overlay_net

  client:
    environment:
      - DECLARED_DECLARATION_SEARCH_QUERY_COUNT=100

  gateway:
    environment:
      - LANGUAGES=en,fr,mg
      - SENTRY_DSN=${SENTRY_DSN:-}
      - COUNTRY=FAR
      - QA_ENV=true
      - NODE_ENV=production

  workflow:
    environment:
      - LANGUAGES=en,fr,mg
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  search:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  metrics:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  auth:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  user-mgnt:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  webhooks:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  config:
    environment:
      - SENTRY_DSN=${SENTRY_DSN:-}
      - QA_ENV=true
      - NODE_ENV=production

  documents:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  scheduler:
    environment:
      - QA_ENV=true
      - NODE_ENV=production
