# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
all:
  vars:
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: my-user
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABg...Z/rhU= user@example.com
        state: present
        sudoer: true

      # @todo will this host be used as a bastion / jump server for the CI/CD pipeline to access production servers?
      # if no, then you can remove this user.
      - name: jump
        ssh_keys:
          # if yes, then this should list the public keys of the private keys that are used when connecting to the production servers.
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABg...Z/rhU= provision@github-runner-243 # example provision user key
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABg...Z/rhU= provision@github-runner-244 # example provision user key

    # If the machine is repurposed to also be the backup host, we need to add more keys to the authorized_keys file so that
    # when the application servers get provisioned, the provision user of this machine can be used.
    #
    # @todo remove this key if the machine is not used as a backup host.
    # Otherwise, add the public key of the private key that's used for the "provision" user on the server of which backups this machine hosts.
    additional_keys_for_provisioning_user:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABg...Z/rhU= provision@github-runner-243 # example provision user key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABg...Z/rhU= provision@github-runner-244 # example provision user key

docker-manager-first:
  hosts:
    qa: # @todo set this to be the hostname of your target server
      ansible_host: '55.55.55.55' # @todo set this to be the IP address of your server
      data_label: data1 # for manager machines, this should always be "data1"

# QA and staging servers are not configured to use workers.
docker-workers: {}
