name: Docker

on:
  push:
    branches:
      - master
      - develop

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: |
          export VERSION=`git log -1 --pretty=format:%h` && bash build-and-push.sh && unset VERSION
