# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Backup from legacy environment

on:
  workflow_dispatch:
    inputs:
      backup-source-environment:
        type: choice
        description: Environment to create backup from
        required: true
        default: legacy-preprod
        options:
          - legacy-preprod
      backup-destination-environment:
        type: choice
        description: Environment to create backups to
        required: true
        default: qa
        options:
          - qa
      replicas:
        description: No of replicas deployed in the environment
        default: '1'
        required: true
      version_label:
        description: The version label for the backups
        required: true
jobs:
  destination-environment-vars:
    environment: ${{ github.event.inputs.backup-destination-environment }}
    runs-on: ubuntu-22.04
    outputs:
      BACKUP_DESTINATION_SSH_HOST: ${{ vars.SSH_HOST || secrets.SSH_HOST }}
      BACKUP_DESTINATION_SSH_PORT: ${{ vars.SSH_PORT || secrets.SSH_PORT }}
      BACKUP_DESTINATION_SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - name: Echo
        run: echo ${{ github.events.inputs.environment }}

  run-backup:
    environment: ${{ github.event.inputs.backup-source-environment }}
    needs: destination-environment-vars
    runs-on: ubuntu-22.04
    steps:
      - name: Clone country config resource package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: './${{ github.event.repository.name }}'

      - name: Read known hosts
        run: |
          cd ${{ github.event.repository.name }}
          echo "KNOWN_HOSTS<<EOF" >> $GITHUB_ENV
          sed -i -e '$a\' ./infrastructure/known-hosts
          cat ./infrastructure/known-hosts >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ env.KNOWN_HOSTS }}

      - name: Create backup data in given environment and copy it over to the backup environment
        env:
          BACKUP_SOURCE_SSH_HOST: ${{ vars.SSH_HOST || secrets.SSH_HOST }}
          BACKUP_SOURCE_SSH_PORT: ${{ vars.SSH_PORT || secrets.SSH_PORT }}
          BACKUP_SOURCE_SSH_USER: ${{ secrets.SSH_USER }}
          BACKUP_DESTINATION_SSH_HOST: ${{ needs.destination-environment-vars.outputs.BACKUP_DESTINATION_SSH_HOST }}
          BACKUP_DESTINATION_SSH_PORT: ${{ needs.destination-environment-vars.outputs.BACKUP_DESTINATION_SSH_PORT }}
          BACKUP_DESTINATION_SSH_USER: ${{ needs.destination-environment-vars.outputs.BACKUP_DESTINATION_SSH_USER }}
        run: |
          ssh $BACKUP_SOURCE_SSH_USER@$BACKUP_SOURCE_SSH_HOST -p $BACKUP_SOURCE_SSH_PORT "\
          bash infrastructure/backup.sh \
          --ssh_host=$BACKUP_DESTINATION_SSH_HOST
          --ssh_port=$BACKUP_DESTINATION_SSH_PORT
          --ssh_user=$BACKUP_DESTINATION_SSH_USER \
          --remote_dir=/data/backup \
          --replicas=1 \
          --label=${{ github.event.inputs.version_label }} >> /var/log/opencrvs-backup.log 2>&1"
