# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
<<<<<<< HEAD
name: Take backup from legacy environment
=======
name: Backup from legacy environment
>>>>>>> develop

on:
  workflow_dispatch:
    inputs:
      backup-source-environment:
        type: choice
<<<<<<< HEAD
        description: Environment to export backup from
=======
        description: Environment to create backup from
>>>>>>> develop
        required: true
        default: legacy-preprod
        options:
          - legacy-preprod
      backup-destination-environment:
        type: choice
<<<<<<< HEAD
        description: Environment to import backups to
=======
        description: Environment to create backups to
>>>>>>> develop
        required: true
        default: qa
        options:
          - qa
      replicas:
        description: No of replicas deployed in the environment
        default: '1'
        required: true
      version_label:
        description: The version label for the backups
        required: true

jobs:
  destination-ssh-user:
    name: Get destination SSH user
    uses: ./.github/workflows/get-secret-from-environment.yml
    with:
      secret_name: 'SSH_USER'
      env_name: ${{ github.event.inputs.backup-destination-environment }}
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      encryption_key: ${{ secrets.GH_ENCRYPTION_PASSWORD }}
      SSH_USER: ${{ secrets.SSH_USER }}

  destination-environment-vars:
    environment: ${{ github.event.inputs.backup-destination-environment }}
    runs-on: ubuntu-22.04
    outputs:
      BACKUP_DESTINATION_SSH_HOST: ${{ vars.SSH_HOST || secrets.SSH_HOST }}
      BACKUP_DESTINATION_SSH_PORT: ${{ vars.SSH_PORT || secrets.SSH_PORT }}
    steps:
      - name: Echo
        run: echo ${{ github.events.inputs.backup-destination-environment }}

  run-backup:
    environment: ${{ github.event.inputs.backup-source-environment }}
    needs: [destination-ssh-user, destination-environment-vars]
    runs-on: ubuntu-22.04
    env:
      BACKUP_SOURCE_SSH_HOST: ${{ vars.SSH_HOST || secrets.SSH_HOST }}
      BACKUP_SOURCE_SSH_PORT: ${{ vars.SSH_PORT || secrets.SSH_PORT }}
      BACKUP_SOURCE_SSH_USER: ${{ secrets.SSH_USER }}
      BACKUP_DESTINATION_SSH_HOST: ${{ needs.destination-environment-vars.outputs.BACKUP_DESTINATION_SSH_HOST }}
      BACKUP_DESTINATION_SSH_PORT: ${{ needs.destination-environment-vars.outputs.BACKUP_DESTINATION_SSH_PORT }}
      BACKUP_RAW_FILES_DIR: /tmp/backup-${{ github.event.inputs.version_label }}
    steps:
      - name: Insert destination SSH user to environment variables
        run: |
          echo "${{ needs.destination-ssh-user.outputs.secret_value }}" | base64 --decode | \
          openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}" -out /tmp/backup_destination_ssh_user
          BACKUP_DESTINATION_SSH_USER=$(cat /tmp/backup_destination_ssh_user)
          echo "BACKUP_DESTINATION_SSH_USER=$BACKUP_DESTINATION_SSH_USER" >> $GITHUB_ENV

      - name: Clone country config resource package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: './${{ github.event.repository.name }}'

      - name: Read known hosts
        run: |
          cd ${{ github.event.repository.name }}
          echo "KNOWN_HOSTS<<EOF" >> $GITHUB_ENV
          sed -i -e '$a\' ./infrastructure/known-hosts
          cat ./infrastructure/known-hosts >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install SSH Key for source environment
        uses: shimataro/ssh-key-action@v2
        with:
          name: id_rsa-source
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ env.KNOWN_HOSTS }}

      - name: Create backup data in given environment and copy it over to the backup environment
        run: |
          cd ${{ github.event.repository.name }}
          scp -i ~/.ssh/id_rsa-source -P $BACKUP_SOURCE_SSH_PORT infrastructure/backups/legacy-backup.sh $BACKUP_SOURCE_SSH_USER@$BACKUP_SOURCE_SSH_HOST:/tmp/
          ssh -i ~/.ssh/id_rsa-source $BACKUP_SOURCE_SSH_USER@$BACKUP_SOURCE_SSH_HOST -p $BACKUP_SOURCE_SSH_PORT "\
          sudo bash /tmp/legacy-backup.sh \
          --ssh_host=$BACKUP_DESTINATION_SSH_HOST \
          --ssh_user=$BACKUP_DESTINATION_SSH_USER \
          --ssh_port=$BACKUP_DESTINATION_SSH_PORT \
          --remote_dir=$BACKUP_RAW_FILES_DIR \
          --replicas=${{ github.event.inputs.replicas }} \
          --label=${{ github.event.inputs.version_label }} >> /var/log/opencrvs-backup-${{ github.event.inputs.version_label }}.log 2>&1"
