# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Restore environment to backup

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to restore
        required: true
        default: qa
        options:
          - qa
      version_label:
        description: Version label for backup
        required: true
      replicas:
        description: No of replicas deployed in the environment
        default: '1'
        required: true
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo
        run: echo workflow must be in main branch
