name: E2E
run-name: Deploy to ${{ github.event.inputs.environment }} and E2E
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        required: true
        default: 'development'
        options:
          - development
      core-image-tag:
        description: Core DockerHub image tag
        required: true
        default: 'v1.4.1'
      countryconfig-image-tag:
        description: Your Country Config DockerHub image tag
        required: true
        default: 'v1.4.1'
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      core-image-tag: ${{ github.event.inputs.core-image-tag }}
      countryconfig-image-tag: ${{ github.event.inputs.countryconfig-image-tag }}
      reset: true
    secrets: inherit
  test:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js 18.19
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'
          cache: 'npm'

      - name: Runs dependency installation
        run: yarn

      - name: Run tests
        run: |
          export CYPRESS_COUNTRYCONFIG_URL=https://countryconfig.${{ vars.DOMAIN }}/
          export CYPRESS_GATEWAY_URL=https://gateway.${{ vars.DOMAIN }}/
          export CYPRESS_LOGIN_URL=https://login.${{ vars.DOMAIN }}/
          export CYPRESS_CLIENT_URL=https://register.${{ vars.DOMAIN }}/
          export CYPRESS_AUTH_URL=https://auth.${{ vars.DOMAIN }}/
          npx cypress run
