name: Seed data
run-name: Seed data to ${{ github.event.inputs.environment }} core=${{ github.event.inputs.core-image-tag }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      core-image-tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to seed data
        required: true
        default: 'development'
        options:
          - development
          - qa
          - staging
          - production
      core-image-tag:
        description: Core DockerHub image tag
        required: true
jobs:
  seed-data:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    
    steps:
      - name: Run the data-seeder container
        uses: addnab/docker-run-action@v3
        with:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
           registry: gcr.io
           image: ocrvs-data-seeder:${{ github.event.inputs.core-image-tag }}
           run: yarn seed:prod
           env: |
             ACTIVATE_USERS=${{ vars.ACTIVATE_USERS }}
             GATEWAY_HOST=${{ vars.GATEWAY_HOST }}
             AUTH_HOST=${{ vars.AUTH_HOST }}
             COUNTRY_CONFIG_HOST=${{ vars.COUNTRY_CONFIG_HOST }}
             SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }}

